# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 17:16
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guard', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='application',
            old_name='key',
            new_name='personal_id',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='application',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guard.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Application'),
        ),
        migrations.AddField(
            model_name='team',
            name='publications',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Application'),
        ),
    ]
