# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordRecoverToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('token', models.TextField(default=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
